metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s

setup.dashboards.enabled: true

setup.kibana:
  host: "localhost:5601"

output.logstash:
  hosts: ["localhost:5044"]
