version: '3.5'

services:
  zoo1:
    image: zookeeper:3.9
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=10.129.0.27:2888:3888;2181 server.3=10.131.0.29:2888:3888;2181 server.4=10.131.0.5:2888:3888;2181

  clickhouse-node1:
    image: clickhouse/clickhouse-server:24.2.1
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /mnt/vdb1/data:/var/lib/clickhouse/
      - ./data/node1:/etc/clickhouse-server
    depends_on:
      - zoo1
