# Generated by Django 4.2.4 on 2023-08-22 18:01

from django.db import migrations

import psqlextra.indexes.unique_index


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_filmwork_file_path"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="personfilmwork",
            name="film_work_person_idx",
        ),
        migrations.AddIndex(
            model_name="personfilmwork",
            index=psqlextra.indexes.unique_index.UniqueIndex(
                fields=["film_work", "person", "role"],
                name="film_work_person_role_idx",
            ),
        ),
    ]
