---
version : "3.9"

services:
  logstash:
    image: logstash:8.12.2
    environment:
      # Так как сейчас вы хотите запустить logstash без Elasticsearch, необходимо отключить встроенный мониторинг, отправляющий данные в ES
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      # Указываем ES запуститься в одном экземпляре
      - discovery.type=single-node
      # Пока не будем беспокоиться о безопасности
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./deploy/esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ CMD-SHELL, curl -s http://127.0.0.1:9200/_cluster/health]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

#  filebeat:
#    image: elastic/filebeat:8.12.2
#    volumes:
#      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
#    depends_on:
#      - logstash
#      - elasticsearch
#      - kibana
#    links:
#      - logstash


#  metricbeat:
#    image: elastic/metricbeat:8.12.2
#    volumes:
#      - ./deploy/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
#    depends_on:
#      - logstash
#      - elasticsearch
#      - kibana
#    links:
#      - logstash

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
