version: '3.5'

services:
  zoo2:
    image: zookeeper:3.9
    restart: always
    hostname: zoo2
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=10.128.0.4:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=10.131.0.29:2888:3888;2181 server.4=10.131.0.5:2888:3888;2181

  clickhouse-node2:
    image: clickhouse/clickhouse-server:24.2.1
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - /mnt/vdb1/data:/var/lib/clickhouse/
      - ./data/node2:/etc/clickhouse-server
    depends_on:
      - zoo2
