version: '3.5'

services:
  zoo3:
    image: zookeeper:3.9
    restart: always
    hostname: zoo3
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=10.128.0.4:2888:3888;2181 server.2=10.129.0.27:2888:3888;2181 server.3=zoo3:2888:3888;2181 server.4=10.131.0.5:2888:3888;2181

  clickhouse-node3:
    image: clickhouse/clickhouse-server:24.2.1
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - /mnt/vdb1/data:/var/lib/clickhouse/
      - ./data/node3:/etc/clickhouse-server
    depends_on:
      - zoo3
