---
version        : '3.9'

x-base-settings: &base-settings
  env_file: ./.env
  restart: always

services       :
  kafka-0:
    image: bitnami/kafka:3.6.1
    ports:
    -   9094:9094
    environment:
    -   KAFKA_ENABLE_KRAFT=yes
    -   ALLOW_PLAINTEXT_LISTENER=yes
    -   KAFKA_CFG_NODE_ID=0
    -   KAFKA_CFG_PROCESS_ROLES=broker,controller
    -   KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    -   KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
    -   KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    -   KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    -   KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9094
    -   KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    healthcheck:
      test: [CMD-SHELL, kafka-topics.sh --bootstrap-server localhost:9094 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server localhost:9094
            --topic hc --describe]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
    -   kafka_0_data:/bitnami/kafka


  kafka-1:
    image: bitnami/kafka:3.6.1
    ports:
    -   9095:9094
    environment:
    -   KAFKA_ENABLE_KRAFT=yes
    -   ALLOW_PLAINTEXT_LISTENER=yes
    -   KAFKA_CFG_NODE_ID=1
    -   KAFKA_CFG_PROCESS_ROLES=broker,controller
    -   KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    -   KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
    -   KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    -   KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    -   KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9095
    -   KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

    volumes:
    -   kafka_1_data:/bitnami/kafka

  kafka-2:
    image: bitnami/kafka:3.6.1
    ports:
    -   9096:9094
    environment:
    -   KAFKA_ENABLE_KRAFT=yes
    -   ALLOW_PLAINTEXT_LISTENER=yes
    -   KAFKA_CFG_NODE_ID=2
    -   KAFKA_CFG_PROCESS_ROLES=broker,controller
    -   KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    -   KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
    -   KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    -   KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    -   KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:9096
    -   KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
    -   kafka_2_data:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.7.1
    ports:
    -   8080:8080
    environment:
    -   KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092
    -   KAFKA_CLUSTERS_0_NAME=kraft

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
    -   8123:8123   # HTTP интерфейс
    -   9000:9000   # Нативный клиентский интерфейс
    -   9009:9009   # GRPC интерфейс (если будет использоваться)
    volumes:
    -   ./init_sql:/docker-entrypoint-initdb.d
    -   clickhouse_data:/var/lib/clickhouse
    -   clickhouse_log:/var/log/clickhouse-server
    -   clickhouse_config:/etc/clickhouse-server
    healthcheck:
      test: [CMD-SHELL, clickhouse-client --query "SELECT 1"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  etl:
    <<: *base-settings
    build: .
    depends_on:
      kafka-0:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

volumes        :
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
  clickhouse_data:
  clickhouse_log:
  clickhouse_config:
